services:
  - type: web
    name: my-app
    env: node
    region: us-central
    branch: main
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: "18"
