services:
  - type: web
    name: my-service
    env: java
    buildCommand: ./render-build.sh
    startCommand: java -jar build/libs/my-service.jar
    javaVersion: "17"
    envVars:
      - key: JAVA_HOME
        value: "/usr/lib/jvm/java-17-openjdk"
      - key: DATABASE_URL
        value: "jdbc:postgresql://your-database-url"
