services:
  - type: web
    name: my-service
    env: node
    buildCommand: |
      # Instalar Java 17 usando Chocolatey
      choco install -y openjdk --version=17.0.12
      # Configurar JAVA_HOME
      export JAVA_HOME=$(dirname $(dirname $(which java)))
      ./gradlew build
    startCommand: npm start
