services:
  - type: web
    name: my-service
    env: java
    buildCommand: ./gradlew build
    startCommand: java -jar build/libs/my-service.jar
    javaVersion: "17"
    envVars:
      - key: JAVA_HOME
        value: "/usr/lib/jvm/java-17-openjdk"
      - key: API_KEY
        value: "your-api-key-here"
      - key: DATABASE_URL
        value: "jdbc:postgresql://your-database-url"
      - key: SECRET_KEY
        value: "your-secret-key-here"